### ISSUE TITLE
smooth histogram curves

### ISSUE THREAD

**Issue by khiopsrelease** [khiopsrelease/kv-release#124]
•	L’histogramme n’est pas « lissse », alors qu’il le devrait (cf. courbe en bleue ci-dessous obtenue rapidement avec le fichier excel ci-joint pour les x positifs
o	Probablement le même bug qu’avec la loi gaussienne

![image](https://github.com/khiopsrelease/kv-release/assets/50991455/5baf458d-dccd-4354-84ad-58fcd7af7d46)

**Comment by stephanebouget** [comment]
ok avec la modif de la formule de calcul de la densité

![image](https://github.com/khiopsrelease/kv-release/assets/13203455/1e093bca-a74e-42fb-9023-ae2ffc45bd41)
