### ISSUE TITLE
Double click on .khj files does not work in macOS

### ISSUE THREAD

**Issue by folmos-at-orange** [khiopsrelease/kv-release#150]
**Describe the bug**
Doing double-click on `.khj` files opens the khiops viz app but it doesn't load the data. It only shows the "open a file from the menu" message as if it were open by clicking the khiops viz icon.

**Platform / versions (please complete the following information):**
 - Platform: macOS Venture 13.5.2
 - Version: 11.0.2
 - Khiops Lib Version: ?

**Comment by stephanebouget** [comment]
idem sous win : 
![image](https://github.com/khiopsrelease/kv-release/assets/13203455/bfb81de5-3a8f-4cae-8e08-97ff4e08b5e4)
