### ISSUE TITLE
bug sur la couleur de visualisation des courbes de ROC

### ISSUE THREAD

**Issue by stephanebouget** [khiopsrelease/kv-release#26]
Quand on décoche les courbes à afficher (Filter curves). Il y a un décalage de couleurs entre la légende et les info-bulles quand on décoche par le haut (ex : Population) ou au milieu. 
Quand on décoche par la fin de manière contigüe, on n’a pas le problème.

Version: 10.1.4
Khiops lib version: 1.2.3

**Comment by khiopsrelease** [comment]
au passage : amélioration des couleurs des courbes pour mieux contraster
