### ISSUE TITLE
Revoir la gestion des échelles

### ISSUE THREAD

**Issue by khiopsrelease** [khiopsrelease/kv-release#4]
**Describe the feature**
visualisations bivariées en supervisé et non supervisé (Preparation2DWithOdor.results.zip), en comparant la visualiasation V9 et V10. 

•	Les cases en bleus en V10 me semblent trop foncé
o	Il me semble que le problème provient de ce qu’en V10, l’échelle est ajustée entre le min et le max des valeurs de la matrice, localement à la valeur cible choisie, et localement à la paire

o	En V9, c’est compris entre min(absolute max) et max(absolute max), avec absolute max = max(|max value| ; |min value|), ce qui permet de visualiser les valeurs positives et négatives sur une échelle « commensurable »
o	De plus, ces min et max sont calculés sur l’ensemble de toutes les valeurs de Target, et pour toutes les paires, pour avoir une seul échelle globale pour toutes les paire et de pouvoir les comparer visuellement simplement
	Sinon, si les échelles sont auto-ajustée localement, on a l’impression que les paires très peu informatives sont très contrastée, uniquement par ce que les couleurs sont projetée aux extrémités d’une échelle locale

•	La palette de couleur et la gestion du contraste est vraiment différente : je m’étais habitué à la V9, mais ce n’est peut-être qu’une question d’habitude
o	Je crois que ce qui me gêne le plus est que le rouge le plus intense est marron

Preparation2DWithOdor, supervisé, paire Odor x Population, I(POISONOUS|Polulation, Odor), Visualisation V9
Le min et le max de l’échelle sont calculés sur l’ensemble de toutes les paires, pour avoir une seule échelle globale est comparer toutes les informations de façon commensurable.
![image](https://user-images.githubusercontent.com/50991455/122559257-6458f280-d03f-11eb-8288-cda1aaf7a53b.png)

 

Preparation2DWithOdor, supervisé, paire Odor x Population, I(POISONOUS|Polulation, Odor), Visualisation V10
L’échelle n’est pas symétrique sur les valeurs positive et négative, et change selon la valeur de la classe cible.
Le libellé dans les info-bulle est incorrect.
![image](https://user-images.githubusercontent.com/50991455/122559242-60c56b80-d03f-11eb-85bb-3517b659d8b7.png)

**Comment by stephanebouget** [comment]
Il y a trois niveaux d’amélioration possible dont deux me semblent « pas chers » et le troisième plus coûteux (nettement)
1-	Pour une paire et une valeur de cible, utiliser la même échelle pour les valeurs positives et négatives (donc aller de –max(|valeur|) à +max(|valeur|)) ; cela permet effectivement d’avoir visuellement les influences positives et négatives de façon immédiate
2-	Faire la même chose pour une paire donnée mais en utilisant une échelle commune pour toutes les valeurs de la cible (donc en allant de –E à +E où E = max(|valeurC1|,|valeurC2|,|valeurC3|, …) avec C1, C2, C3, … sont les valeurs de la cible) ; cela permet de comparer visuellement  l’influence d’une paire sur les différentes valeurs de la cible
3-	Faire la même chose mais en prenant en plus le max sur l’ensemble des paires ; c’est potentiellement beaucoup plus coûteux car le nombre de paires peut être (en théorie) très  grand ; cela dit, c’est un calcul de max, cela peut aller assez vite et en une passe.

Pour commencer, je ferais bien les points 1 et 2 (en fait 2 directement !). Pour le point 3, dis-moi si tu penses que c’est lourd de calculer le max sur l’ensemble des paires ; on fait bien des opérations sur l’ensemble des variables comme les tris de façon dynamique et cela marche impeccablement ! Là, en plus, c’est une opération qu’on ne fait qu’une fois, au chargement.
