### ISSUE TITLE
Ajout d'infos dans l'onglet project

### ISSUE THREAD

**Issue by khiopsrelease** [khiopsrelease/kv-release#6]
**Describe the feature**
L’onglet Project ne contient pour l’instant que l’information sur la Database.
Je pense que l’on pourrait le compléter avec les informations suivantes, issues pour la plupart du panneau « Summary » de « Preparation » :
•	Short description (si spécifié dans le json)
•	Database
•	Learning task
•	Target variable
•	Instances
•	Variables

Le nombre de variables est à calculer à partir de la section « variables » du .json (cf. ci-dessous dans le mail, extrait du fichier joint EmptyDatabaseReports.khj).
C’est le nombre total de variables de type Numerical » ou « Categorical » (on ignore les autres type « Time », « Date »,…), auquel on retranche 1 si la « targetVariable » est non vide. Dans l’exemple joint, on a (1+7)  -1 = 7.
Cela coïncide avec la valeur de « evaluatedVariables » quand elle est disponible, mais on peut ainsi avoir des information synthériques, même dans le cas à effet de bord d’une base vide.

On pourrait également ajouter la liste des logs dans cet onglet Project, dans le cas où il y en a (cf. fichier joint AllReportWithLogs.khj, section "logs" du .json).
Dans ce cas, un tableau à deux colonne (« Task », « Message ») semble adapté.

                "preparationReport": {
                               "reportType": "Preparation",
                               "summary": {
                                               "dictionary": "Database",
                                               "variables": {
                                                               "types": [
                                                                              "Categorical",
                                                                              "Numerical"
                                                               ],
                                                               "numbers": [
                                                                              1,
                                                                              7
                                                               ]
                                               },
                                               "database": ".\/..\/Standard\/DatabaseEmpty.txt",
                                               "samplePercentage": 70,
                                               "samplingMode": "Include sample",
                                               "selectionVariable": "",
                                               "selectionValue": "",
                                               "instances": 0,
                                               "learningTask": "Classification analysis",
                                               "targetVariable": "Class",
                                               "targetDescriptiveStats": {
                                                               "values": 0,
                                                               "mode": "",
                                                               "modeFrequency": 0
                                               },
                                               "targetValues": {
                                                               "values": [],
                                                               "frequencies": []
                                               }
                               }
                }

**Comment by stephanebouget** [comment]
![image](https://user-images.githubusercontent.com/13203455/126495793-db6e5440-7744-4e9d-8138-d8984dafc26e.png)
