### ISSUE TITLE
The leaf sizes are too large

### ISSUE THREAD

**Issue by felipe-olmos-orange** [khiopsrelease/kv-release#71]
#### Description

The leaf sizes are too large for certain tree visualizations when they are set by population. Attached you'll find an example report.

![image](https://user-images.githubusercontent.com/92923444/190092757-2adbf0b0-6657-4c93-8c66-482355efe820.png)

---
Version: 10.2.8
[AllReports.zip](https://github.com/khiopsrelease/kv-release/files/9563950/AllReports.zip)

Khiops lib version: 1.4.9

**Comment by stephanebouget** [comment]
A max relative diameter is now set to this (responsive) size 
![image](https://user-images.githubusercontent.com/13203455/190357097-e8d09b65-605b-416e-b021-9130daf54791.png)
